### PR TITLE
Migrate to GitHub Actions

### PR DESCRIPTION
**Pull request by athomas**

### CODE REVIEW

**Comment by athomas** [comment]
How important is it to analyze on 2.2.0? I could make it work, if needed.

**Comment by jakemac53** [comment]
It would be good to run on stable as well (all tests or just analyzer, but this package is small so we might as well run all tests).

**Comment by athomas** [comment]
> It would be good to run on the oldest supported stable as well (all tests or just analyzer, but this package is small so we might as well run all tests).

The migrated workflow runs the tests on the old stable, but doesn't run the analyzer.

**Review by jakemac53 — APPROVED** [review]

**Comment by jakemac53** [comment]
> The migrated workflow runs the tests on the old stable, but doesn't run the analyzer.

ah ok that should be a stronger check that running the tests, and we don't care about hints/lints triggering on old sdks.

**Pull request merged**
